//
//  ExchangeRate.swift
//  NetworkData
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

import Domain

extension ExchangeRate: EntityType {
    
    enum Key: CodingKey {
        case ask, bid, last, high, low
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Key.self)
        let ask = try container.decode(Domain.ExchangeRate.T.self, forKey: .ask)
        let bid = try container.decode(Domain.ExchangeRate.T.self, forKey: .bid)
        let high = try container.decode(Domain.ExchangeRate.T.self, forKey: .high)
        let last = try container.decode(Domain.ExchangeRate.T.self, forKey: .last)
        let low = try container.decode(Domain.ExchangeRate.T.self, forKey: .low)
        self.init(ask: ask, bid: bid, last: last, high: high, low: low)
    }
}
