//
//  BalanceExtension.swift
//  EOSAccount
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

import struct Domain.Balance

extension Balance {
    
    var totalToString: String {
        return String(format: "%.2f", total)
    }
    
    var toUsdToString: String {
        if let rate = toUsdExchange?.last {
            let value = total * rate
            let numberFormatter = NumberFormatter()
            numberFormatter.numberStyle = .currency
            let usLocale = Locale(identifier: "en_US")
            numberFormatter.locale = usLocale
            return "≈ \(numberFormatter.string(from: NSNumber(value: value)) ?? "-")"
        }
        return "-"
    }
}
