//
//  UserExtension.swift
//  EOSAccount
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

import Domain

extension Optional where Wrapped == Domain.UserType {
    
    var fullname: String {
        return self?.fullname ?? "-"
    }
    
    var eosTotal: String {
        return self?.balance.totalToString ?? "-"
    }
    
    var toUsd: String {
        return self?.balance.toUsdToString ?? "-"
    }
}

extension Domain.UserType {

    func copied(fullname: String? = nil,
                netSelfStaked: Double? = nil, cpuSelfStaked: Double? = nil,
                balance: Balance? = nil,
                net: Сonsumption? = nil, cpu: Сonsumption? = nil,
                ram: Сonsumption? = nil) -> User {
        return User(fullname: fullname ?? self.fullname,
                    netSelfStaked: netSelfStaked ?? self.netSelfStaked,
                    cpuSelfStaked: cpuSelfStaked ?? self.cpuSelfStaked,
                    balance: balance ?? self.balance,
                    net: net ?? self.net,
                    cpu: cpu ?? self.cpu,
                    ram: ram ?? self.ram)
    }
}
