//
//  ExchangeUseCaseProvider.swift
//  NetworkData
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

import Domain

public final class ExchangeUseCaseProvider: Domain.UseCaseProvider {
    
    private let repository: Repository
    
    public init(url: String = "https://apiv2.bitcoinaverage.com/") {
        repository = Repository(url: url, defaultParams: [:])
    }
    
    public var useCase: Domain.ExchangeUseCase {
        return ExchangeUseCase(repository: repository)
    }
}
