//
//  ExchangeUseCase.swift
//  NetworkData
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

import Domain

final class ExchangeUseCase<Repository: ApiRepository>: Domain.ExchangeUseCase {
    
    //MARK: - Properties
    //MARK: Private

    private let repository: Repository
    
    //MARK: - Lifecycle
    
    init(repository: Repository) {
        self.repository = repository
    }
    
    //MARK: - Domain.BalanceUseCase
    
    func rate(_ closure: @escaping Callback<ExchangeRate>) {
        repository.item(ExchangeEndpoint.eosToUsd, nil, closure)
    }
}
