//
//  UserUseCase.swift
//  NetworkData
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

import Domain

final class UserUseCase<Repository: ApiRepository>: Domain.UserUseCase {

    //MARK: - Properties
    //MARK: Private
    
    private let repository: Repository
//    let balanceRepository: Repository
    private let username: String
    
    //MARK: - Lifecycle

    init(_ repository: Repository, username: String) {
        self.repository = repository
        self.username = username
    }
    
    //MARK: - Domain.UserUseCase
    
    func user(_ closure: @escaping (User?, Error?) -> Void) {
        repository.item(EOSEndpoint.account,
                        [ "account_name": username ],
                        closure)
    }
}
