//
//  ApiRepository.swift
//  NetworkData
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation
 
protocol ApiRepository: class {

//    associatedtype Response: Decodable
    
    func item<Response: Decodable>(_ endpoint: EndpointType,
                                   _ parameters: [String : String]?,
                                   _ callback: @escaping (Response?, Error?)->Void)
    func items<Response: Decodable>(_ endpoint: EndpointType,
                                    _ parameters: [String : String]?,
                                    _ callback: @escaping ([Response]?, Error?)->Void)
}
