//
//  ApiError.swift
//  NetworkData
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

enum ApiError: Error {
    case notFound, unknown, incorrectRequest,
    incorrectAccountResponce, incorrectBalanceValue
    
    //TODO: list all error codes and add a localized messages
//    init(code: Int) {
//        switch code {
//        case 404:
//            self = .notFound
//        case -1:
//            self = .incorrectRequest
//        default:
//            self = .unknown
//        }
//    }
}
