//
//  Endpoint.swift
//  NetworkData
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

enum HTTPMethod: String {
    case get = "GET"
    case post = "POST"
}

protocol EndpointType {
    var rawValue: String { get }
    var method: HTTPMethod { get }
}

enum EOSEndpoint: String, EndpointType {
    case account = "v1/chain/get_account"
//    case getBalance = "v1/chain/get_currency_balance"
    
    var method: HTTPMethod {
        return .post
    }
}

enum ExchangeEndpoint: String, EndpointType {
    case eosToUsd = "indices/tokens/ticker/EOSUSD"
    
    var method: HTTPMethod {
        return .get
    }
}
