//
//  ExchangeUseCase.swift
//  Domain
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

public protocol ExchangeUseCase: class {
    
    func rate(_ closure: @escaping Callback<ExchangeRate>)
}
