//
//  UserUseCase.swift
//  Domain
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import Foundation

public typealias Callback<T> = (T?, Error?)->Void

public protocol UserUseCase: class {
    
    func user(_ closure: @escaping Callback<User>)
}
