//
//  UIProgressViewExtension.swift
//  EOSAccount
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import UIKit

extension UIProgressView {

    static func ~>(progress: UIProgressView, binder: Binder<Double>) {
        binder.subscribe { value in
            EOSAccount.mainQueue { progress.progress = Float(value) }
        }
    }
}
