//
//  ConsumptionView.swift
//  EOSAccount
//
//  Created by Marharyta Lytvynenko on 17.11.2019.
//  Copyright (c) 2019 Marharyta Lytvynenko. All rights reserved.
//
//  This file was generated by http://www.popcornomnom.com
//

import UIKit

class ConsumptionView: UIStackView {

    // MARK: - Properties
    
    // MARK: Public

    var viewModel: ConsumptionViewModelType! {
        didSet {
            if let staked = staked {
                staked ~> viewModel.staked
            }
            usage ~> viewModel.usage
            percentage ~> viewModel.percentage
            progress ~> viewModel.progress
        }
    }
    
    // MARK: Outlets
    
    @IBOutlet private weak var staked: UILabel?
    @IBOutlet private weak var usage: UILabel!
    @IBOutlet private weak var percentage: UILabel!
    @IBOutlet private weak var progress: UIProgressView!
}
